name: patchDeployment
pack: kubernetes_gcp
runner_type: python-script
description: "patches a Deployement"
enabled: true
entry_point: "patchDeployment.py"
parameters:
    deployment_name:
      type: string
      required: true
      description: "Name of Deployment to be patched"
    namespace:
      type: string
      description: "Namespace of the Deployment. Default if not mentioned"
      required: false
    patch: 
      type: object
      description: "write the changes you want here"
      required: true